"""
QLoRA fine-tuning script for improving tool-calling on small local models.

Targets Qwen/Qwen2.5-Coder-7B-Instruct from HuggingFace and fine-tunes with
QLoRA (4-bit quantization + LoRA adapters) on the synthetic tool-calling
dataset generated by data_generator.py.

After training, the adapter can be merged back into the base model and
exported to GGUF format for use with Ollama.

Dependencies (installed only when this script runs):
    pip install transformers peft trl datasets bitsandbytes accelerate

Usage:
    # Train
    python -m src.agent.training.finetune --data data/tool_calling_train.jsonl

    # Train + merge + export GGUF
    python -m src.agent.training.finetune --data data/tool_calling_train.jsonl --merge

    # Custom output and epochs
    python -m src.agent.training.finetune --data data/tool_calling_train.jsonl \\
        --output models/my_adapter --epochs 5
"""

from __future__ import annotations

import json
import logging
import subprocess
import sys
from pathlib import Path
from typing import Optional

logger = logging.getLogger("agent.training")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DEFAULT_BASE_MODEL = "Qwen/Qwen2.5-Coder-7B-Instruct"
DEFAULT_OUTPUT_DIR = "models/tool_calling_adapter"
DEFAULT_GGUF_OUTPUT = "models/tool_calling_7b.gguf"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_dataset_from_jsonl(path: str | Path) -> list[dict]:
    """Load ShareGPT-formatted training data from a JSONL file.

    Each line should be a JSON object with a "conversations" key containing
    the message list in ShareGPT format.

    Args:
        path: Path to the JSONL file.

    Returns:
        List of conversation dicts, each with a "conversations" key.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Training data not found: {path}")

    data = []
    with open(path, "r", encoding="utf-8") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                if "conversations" not in obj:
                    logger.warning(f"Line {line_num}: missing 'conversations' key, skipping")
                    continue
                data.append(obj)
            except json.JSONDecodeError as e:
                logger.warning(f"Line {line_num}: invalid JSON ({e}), skipping")
                continue

    logger.info(f"Loaded {len(data)} conversations from {path}")
    return data


def format_conversation_for_qwen(conversation: list[dict]) -> str:
    """Format a ShareGPT conversation into the Qwen chat template.

    Qwen2.5 uses the ChatML format:
        <|im_start|>system
        ...
        <|im_end|>
        <|im_start|>user
        ...
        <|im_end|>
        <|im_start|>assistant
        ...
        <|im_end|>

    The "tool" role is mapped to a user message with a [Tool Result] prefix,
    which matches how the agent injects tool results at inference time.

    Args:
        conversation: List of message dicts with "role" and "content" keys.

    Returns:
        Formatted string ready for tokenization.
    """
    parts = []
    for msg in conversation:
        role = msg["role"]
        content = msg["content"]

        if role == "tool":
            # Map tool results to a user-like message so the model learns
            # to process them and generate a final response
            parts.append(f"<|im_start|>user\n[Tool Result]\n{content}<|im_end|>")
        else:
            parts.append(f"<|im_start|>{role}\n{content}<|im_end|>")

    # Add generation prompt at the end if the last message isn't from assistant
    text = "\n".join(parts)
    return text


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train(
    data_path: str | Path,
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    base_model: str = DEFAULT_BASE_MODEL,
    epochs: int = 3,
    batch_size: int = 4,
    gradient_accumulation_steps: int = 4,
    learning_rate: float = 2e-4,
    warmup_ratio: float = 0.1,
    max_seq_length: int = 2048,
) -> Path:
    """Run QLoRA fine-tuning on the tool-calling dataset.

    Loads the base model in 4-bit quantization, attaches LoRA adapters to
    the attention projection layers, and trains using the SFTTrainer from
    the trl library.

    Args:
        data_path: Path to the JSONL training data file.
        output_dir: Directory to save the LoRA adapter weights.
        base_model: HuggingFace model ID for the base model.
        epochs: Number of training epochs.
        batch_size: Per-device training batch size.
        gradient_accumulation_steps: Steps to accumulate before optimizer update.
        learning_rate: Peak learning rate for the cosine schedule.
        warmup_ratio: Fraction of training steps used for warmup.
        max_seq_length: Maximum sequence length for training examples.

    Returns:
        Path to the saved adapter directory.
    """
    # Lazy imports — these heavy libraries are only needed for training
    from transformers import (
        AutoModelForCausalLM,
        AutoTokenizer,
        BitsAndBytesConfig,
        TrainingArguments,
    )
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
    from trl import SFTTrainer, SFTConfig
    from datasets import Dataset

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Load training data ──────────────────────────────────────────
    raw_data = load_dataset_from_jsonl(data_path)
    formatted_texts = []
    for item in raw_data:
        text = format_conversation_for_qwen(item["conversations"])
        formatted_texts.append({"text": text})

    dataset = Dataset.from_list(formatted_texts)
    logger.info(f"Training dataset: {len(dataset)} examples")

    # ── Quantization config (4-bit QLoRA) ───────────────────────────
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype="float16",
        bnb_4bit_use_double_quant=True,
    )

    # ── Load base model + tokenizer ─────────────────────────────────
    logger.info(f"Loading base model: {base_model}")
    tokenizer = AutoTokenizer.from_pretrained(
        base_model,
        trust_remote_code=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )
    model = prepare_model_for_kbit_training(model)

    # ── LoRA config ─────────────────────────────────────────────────
    # Target the attention projection layers for maximum impact on
    # structured output quality (arXiv:2512.15943 finding)
    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
        bias="none",
        task_type="CAUSAL_LM",
    )

    model = get_peft_model(model, lora_config)
    trainable_params, total_params = model.get_nb_trainable_parameters()
    logger.info(
        f"Trainable parameters: {trainable_params:,} / {total_params:,} "
        f"({100 * trainable_params / total_params:.2f}%)"
    )

    # ── Training arguments ──────────────────────────────────────────
    training_args = SFTConfig(
        output_dir=str(output_dir),
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        learning_rate=learning_rate,
        fp16=True,
        warmup_ratio=warmup_ratio,
        logging_steps=10,
        save_strategy="epoch",
        save_total_limit=2,
        lr_scheduler_type="cosine",
        optim="paged_adamw_8bit",
        max_seq_length=max_seq_length,
        dataset_text_field="text",
        report_to="none",
    )

    # ── Train ───────────────────────────────────────────────────────
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        processing_class=tokenizer,
    )

    logger.info("Starting QLoRA fine-tuning...")
    trainer.train()

    # ── Save adapter ────────────────────────────────────────────────
    model.save_pretrained(str(output_dir))
    tokenizer.save_pretrained(str(output_dir))
    logger.info(f"Adapter saved to {output_dir}")

    return output_dir.resolve()


# ---------------------------------------------------------------------------
# Merge and export
# ---------------------------------------------------------------------------

def merge_and_export(
    adapter_path: str | Path = DEFAULT_OUTPUT_DIR,
    output_path: str | Path = DEFAULT_GGUF_OUTPUT,
    base_model: str = DEFAULT_BASE_MODEL,
) -> Path:
    """Merge LoRA weights into the base model and export to GGUF for Ollama.

    This is a two-step process:
    1. Merge the LoRA adapter weights back into the base model weights
    2. Convert the merged model to GGUF format using llama.cpp's convert script

    The resulting GGUF file can be imported into Ollama with:
        ollama create tool-calling-7b -f Modelfile

    Args:
        adapter_path: Directory containing the saved LoRA adapter.
        output_path: Path for the output GGUF file.
        base_model: HuggingFace model ID of the base model.

    Returns:
        Path to the exported GGUF file.
    """
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel

    adapter_path = Path(adapter_path)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    merged_dir = adapter_path / "merged"
    merged_dir.mkdir(parents=True, exist_ok=True)

    # ── Step 1: Merge adapter into base model ───────────────────────
    logger.info(f"Loading base model: {base_model}")
    base = AutoModelForCausalLM.from_pretrained(
        base_model,
        device_map="auto",
        trust_remote_code=True,
    )
    tokenizer = AutoTokenizer.from_pretrained(base_model, trust_remote_code=True)

    logger.info(f"Loading adapter from: {adapter_path}")
    model = PeftModel.from_pretrained(base, str(adapter_path))

    logger.info("Merging LoRA weights into base model...")
    merged = model.merge_and_unload()

    logger.info(f"Saving merged model to: {merged_dir}")
    merged.save_pretrained(str(merged_dir))
    tokenizer.save_pretrained(str(merged_dir))

    # ── Step 2: Convert to GGUF ─────────────────────────────────────
    # Uses llama.cpp's convert_hf_to_gguf.py script.
    # The user needs llama.cpp cloned somewhere — we check common paths.
    convert_script = _find_llama_cpp_convert()

    if convert_script is None:
        logger.warning(
            "llama.cpp convert script not found. The merged model has been "
            f"saved to {merged_dir}. To convert manually:\n"
            "  python /path/to/llama.cpp/convert_hf_to_gguf.py "
            f"{merged_dir} --outfile {output_path} --outtype q8_0"
        )
        return merged_dir.resolve()

    logger.info(f"Converting to GGUF: {output_path}")
    result = subprocess.run(
        [
            sys.executable,
            str(convert_script),
            str(merged_dir),
            "--outfile", str(output_path),
            "--outtype", "q8_0",
        ],
        capture_output=True,
        text=True,
        timeout=600,
    )

    if result.returncode != 0:
        logger.error(f"GGUF conversion failed:\n{result.stderr}")
        logger.info(f"Merged model is available at: {merged_dir}")
        return merged_dir.resolve()

    logger.info(f"GGUF exported to: {output_path}")
    logger.info(
        "To import into Ollama, create a Modelfile with:\n"
        f"  FROM {output_path}\n"
        "Then run: ollama create tool-calling-7b -f Modelfile"
    )

    return output_path.resolve()


def _find_llama_cpp_convert() -> Optional[Path]:
    """Search common locations for llama.cpp's GGUF conversion script.

    Returns:
        Path to convert_hf_to_gguf.py if found, None otherwise.
    """
    search_paths = [
        Path.home() / "llama.cpp" / "convert_hf_to_gguf.py",
        Path.home() / "git" / "llama.cpp" / "convert_hf_to_gguf.py",
        Path("/opt/llama.cpp/convert_hf_to_gguf.py"),
        Path.cwd() / "llama.cpp" / "convert_hf_to_gguf.py",
        # Also check PATH
    ]

    for p in search_paths:
        if p.exists():
            return p

    # Try to find via which/where
    try:
        result = subprocess.run(
            ["which", "convert_hf_to_gguf.py"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            return Path(result.stdout.strip())
    except Exception:
        pass

    return None


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    """CLI entry point with argparse for training and export."""
    import argparse

    parser = argparse.ArgumentParser(
        description="QLoRA fine-tuning for tool-calling on Qwen2.5-Coder-7B",
    )
    parser.add_argument(
        "--data",
        type=str,
        default="data/tool_calling_train.jsonl",
        help="Path to the JSONL training data (default: data/tool_calling_train.jsonl)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory for the LoRA adapter (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--base-model",
        type=str,
        default=DEFAULT_BASE_MODEL,
        help=f"HuggingFace base model ID (default: {DEFAULT_BASE_MODEL})",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=3,
        help="Number of training epochs (default: 3)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
        help="Per-device batch size (default: 4)",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=2e-4,
        help="Learning rate (default: 2e-4)",
    )
    parser.add_argument(
        "--merge",
        action="store_true",
        help="After training, merge LoRA into base model and export to GGUF",
    )
    parser.add_argument(
        "--gguf-output",
        type=str,
        default=DEFAULT_GGUF_OUTPUT,
        help=f"Output path for GGUF file (default: {DEFAULT_GGUF_OUTPUT})",
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(name)s | %(levelname)s | %(message)s",
    )

    # Run training
    adapter_path = train(
        data_path=args.data,
        output_dir=args.output,
        base_model=args.base_model,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.lr,
    )
    print(f"\nAdapter saved to: {adapter_path}")

    # Optionally merge and export
    if args.merge:
        print("\nMerging and exporting to GGUF...")
        export_path = merge_and_export(
            adapter_path=args.output,
            output_path=args.gguf_output,
            base_model=args.base_model,
        )
        print(f"Export complete: {export_path}")


if __name__ == "__main__":
    main()
