"""UI Theme Tool — lets the bot redesign LocalMind's look.

The bot can override any `--lm-*` design token (colors, fonts, spacing,
radii, shadows). The tool rebuilds frontend/design/theme_overrides.css from
a structured token map; raw CSS injection is rejected. This protects the
app from being broken by accident or by a bad LLM output.

Locking: if ~/LocalMind_Workspace/theme_lock exists, the bot cannot edit
the theme. The user creates it from the Settings UI when they want to
freeze their look.
"""

import logging
import re
from pathlib import Path
from typing import Any, Dict

from .base import BaseTool

logger = logging.getLogger("localmind.tools.ui_theme")

# Repo root inferred from this file's location.
_THIS_FILE = Path(__file__).resolve()
_REPO_ROOT = _THIS_FILE.parents[2]
_THEME_FILE = _REPO_ROOT / "frontend" / "design" / "theme_overrides.css"

_LOCK_FILE = Path.home() / "LocalMind_Workspace" / "theme_lock"

# Whitelisted token name pattern: matches the lm-* custom properties used
# throughout tokens.css. Anything outside this prefix is rejected.
_TOKEN_NAME_RE = re.compile(r"^[a-z][a-z0-9-]{1,60}$")

# Whitelisted token value pattern: hex/rgb/rgba/hsl colors, lengths,
# pure numbers, simple font stacks. Blocks `url(...)`, `expression(...)`,
# `@import`, `\\`, etc. Keeps everything inert CSS.
_VALUE_BLOCKLIST = re.compile(
    r"(url\s*\(|@import|expression\s*\(|javascript:|\\|<|>)",
    re.IGNORECASE,
)


def _value_is_safe(value: str) -> bool:
    if not value or len(value) > 200:
        return False
    if _VALUE_BLOCKLIST.search(value):
        return False
    return True


def _is_locked() -> bool:
    return _LOCK_FILE.exists()


def _render_css(tokens: Dict[str, str]) -> str:
    lines = [
        "/* theme_overrides.css — auto-generated by update_theme tool. */",
        "/* Edit by talking to the bot or via the Settings UI. */",
        ":root {",
    ]
    for k, v in tokens.items():
        lines.append(f"  --lm-{k}: {v};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


class UpdateThemeTool(BaseTool):
    @property
    def name(self) -> str:
        return "update_theme"

    @property
    def description(self) -> str:
        return (
            "Redesign the LocalMind UI by overriding design tokens (colors, fonts, "
            "spacing, radii, shadows). Pass a tokens object like "
            "{\"accent\": \"#ff7a18\", \"surface-1\": \"#0d0d10\"}. Each key maps "
            "to a `--lm-{key}` CSS custom property. The user can lock the theme "
            "from Settings to prevent further changes."
        )

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "tokens": {
                    "type": "object",
                    "description": (
                        "Map of token name -> CSS value. Token name omits the 'lm-' "
                        "prefix. Examples: 'accent', 'surface-1', 'text-primary', "
                        "'font-body', 'radius-md'."
                    ),
                    "additionalProperties": {"type": "string"},
                },
                "reason": {
                    "type": "string",
                    "description": "Why you are changing the theme. Will be logged.",
                },
                "merge": {
                    "type": "boolean",
                    "description": (
                        "If true, merge with existing overrides; if false (default), "
                        "replace the entire override file."
                    ),
                    "default": False,
                },
            },
            "required": ["tokens", "reason"],
        }

    async def execute(
        self,
        tokens: Dict[str, str] = None,
        reason: str = "",
        merge: bool = False,
        **kwargs,
    ) -> dict:
        if _is_locked():
            return {
                "success": False,
                "error": "Theme is locked by the user (theme_lock file exists). Ask them to unlock from Settings.",
            }

        if not isinstance(tokens, dict) or not tokens:
            return {"success": False, "error": "Provide a non-empty 'tokens' object."}

        rejected: list[str] = []
        accepted: Dict[str, str] = {}

        for raw_key, raw_val in tokens.items():
            key = str(raw_key or "").strip().lstrip("-").lower()
            if key.startswith("lm-"):
                key = key[3:]
            val = str(raw_val or "").strip().rstrip(";")
            if not _TOKEN_NAME_RE.match(key):
                rejected.append(f"{raw_key} (invalid name)")
                continue
            if not _value_is_safe(val):
                rejected.append(f"{raw_key} (unsafe value)")
                continue
            accepted[key] = val

        if not accepted:
            return {
                "success": False,
                "error": "No valid tokens after validation.",
                "rejected": rejected,
            }

        if merge:
            existing = _parse_existing_overrides()
            existing.update(accepted)
            accepted = existing

        try:
            _THEME_FILE.parent.mkdir(parents=True, exist_ok=True)
            _THEME_FILE.write_text(_render_css(accepted), encoding="utf-8")
            logger.info(
                "Theme updated by bot (%d tokens, reason: %s)",
                len(accepted),
                reason or "unspecified",
            )
            try:
                from backend.observability.activity_log import ActivityKind, record
                token_preview = ", ".join(f"--lm-{k}={v}" for k, v in list(accepted.items())[:3])
                record(
                    ActivityKind.THEME_CHANGE,
                    f"Theme: {len(accepted)} token(s) [{token_preview}]",
                    actor="bot",
                    detail={"reason": reason, "tokens": accepted, "rejected": rejected},
                    success=True,
                )
            except Exception:
                pass
        except OSError as exc:
            return {"success": False, "error": f"Write failed: {exc}"}

        return {
            "success": True,
            "result": (
                f"Theme rebuilt with {len(accepted)} token(s). "
                f"Refresh the page to see changes."
                + (f" Rejected: {', '.join(rejected)}." if rejected else "")
            ),
            "accepted": list(accepted.keys()),
            "rejected": rejected,
        }


def _parse_existing_overrides() -> Dict[str, str]:
    """Best-effort parse of the existing override file so merge=True works."""
    if not _THEME_FILE.exists():
        return {}
    try:
        text = _THEME_FILE.read_text(encoding="utf-8")
    except OSError:
        return {}
    out: Dict[str, str] = {}
    for line in text.splitlines():
        m = re.match(r"\s*--lm-([a-z0-9-]+)\s*:\s*([^;]+);", line)
        if m:
            out[m.group(1)] = m.group(2).strip()
    return out
